Repository Bapull/project_CodingSupporter-react-deployment-repo, pull requests merged in 2024-12, with the labels that each got.

#68 Feature/ment chat
  Dockerfile
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/Alarm.tsx
  src/pages/Feedback.tsx
  src/pages/MenTChat.tsx
  src/pages/User.tsx
  src/styles/menTChat.css
  src/styles/user.css
  src/test/ChatRoomDetail.tsx
Labels: ⭐ Feature

#69 Feature/notification
  package-lock.json
  package.json
  src/App.tsx
  src/hooks/notification.ts
  src/test/GetNoteName.tsx
  src/test/Notification.tsx
Labels: ⭐ Feature

#71 Feature/folder page
  package-lock.json
  package.json
  public/images/Folder-black.png
  public/images/Foldere-open-black.png
  src/pages/Folder.tsx
  src/styles/folder.css
Labels: ⭐ Feature, 🎨 Html & Css

#72 Feature/alarm
  public/images/Bell.png
  public/images/Call.png
  public/images/Mail.png
  public/images/Where.png
  src/App.css
  src/App.tsx
  src/components/Alarm.tsx
  src/components/HeadTitle.tsx
  src/components/Navbar.tsx
  src/hooks/notification.ts
  src/pages/MenTChat.tsx
  src/settings/ContactInfo.tsx
  src/styles/menTChat.css
  src/styles/settings.css
  src/test/ChatRoom.tsx
  src/test/Notification.tsx
Labels: ⭐ Feature

#73 Enhancement/feedback
  package-lock.json
  public/images/Loading.gif
  src/components/Loading.tsx
  src/components/styles/loading.css
  src/pages/Feedback.tsx
  src/pages/FirstUser.tsx
  src/pages/Folder.tsx
Labels: 💡 Enhancement, 🎨 Html & Css
