Repository Bapull/project_CodingSupporter-react-deployment-repo, pull requests merged in 2024-11, with the labels that each got.

#36 CI/CD 파일 및 Docker 파일 포트 설정 변경
  .github/workflows/main.yml
  Dockerfile
Labels: 🐛 BugFix, 🚀 Deploy, 🛠️ Refactor

#37 VITE_API_URL 환경 변수 추가
  .github/workflows/main.yml
Labels: 🐛 BugFix, 🚀 Deploy, 🛠️ Refactor

#42 GitHub Actions 설정 최적화 및 Docker 파일 개선
  .github/workflows/main.yml
  Dockerfile
Labels: 🐛 BugFix, 🚀 Deploy, 🛠️ Refactor

#44 채팅 테스트 페이지 추가
  package-lock.json
  package.json
  src/App.tsx
  src/test/ChatTest.tsx
  src/test/MentoDetail.tsx
  src/test/MentoTest.tsx
  src/test/Notification.tsx
  src/test/NotificationDetail.tsx
  src/test/UserTest.tsx
Labels: ✅ Test

#46 메시지 여러번 뜨는 문제 해결
  package-lock.json
  src/test/ChatTest.tsx
Labels: 🐛 BugFix

#48 GitHub Actions에서 Docker 빌드 실패 오류 수정
  Dockerfile
Labels: 🐛 BugFix, 🚀 Deploy, 🛠️ Refactor

#49 [STYLE] 전체적인 스타일을 일관되게 유지
  src/App.css
  src/styles/settings.css
  src/styles/user.css
Labels: 🎨 Html & Css

#50 Docker 이미지 빌드 오류 수정
  Dockerfile
Labels: 🐛 BugFix, 🚀 Deploy, 🛠️ Refactor

#51 Dockerfile 빌드 최적화 및 배포 이미지 경량화
  Dockerfile
Labels: 🐛 BugFix, 🚀 Deploy, 🛠️ Refactor

#52 Dockerfile 빌드 파일 수정
  Dockerfile
Labels: 🐛 BugFix, 🚀 Deploy, 🛠️ Refactor

#53 [BUG] Added environment variable files and optimized import statements
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/components/charts/Barchart.tsx
  src/components/charts/Calendar.tsx
  src/components/charts/Piechart.tsx
  src/pages/Feedback.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/User.tsx
Labels: 🐛 BugFix, 🛠️ Refactor

#55 notification을 chatroom으로 변경하고, 로그아웃도 겸사겸사 변경
  src/App.tsx
  src/pages/User.tsx
  src/test/ChatRoom.tsx
  src/test/ChatRoomDetail.tsx
  src/test/ChatTest.tsx
  src/test/MentoDetail.tsx
  src/test/Notification.tsx
Labels: 🛠️ Refactor, ✅ Test

#58 [BUG] Removed unused import statements to resolve deployment issues
  src/pages/User.tsx
  src/test/ChatRoom.tsx
  src/test/ChatRoomDetail.tsx
  src/test/ChatTest.tsx
  src/test/MentoDetail.tsx
  src/test/MentoTest.tsx
  src/test/UserTest.tsx
Labels: 🐛 BugFix

#59 Feature/first user
  .gitignore
  Dockerfile
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/HeadTitle.tsx
  src/components/charts/Barchart.tsx
  src/pages/FirstUser.tsx
  src/pages/Home.tsx
  src/pages/User.tsx
  src/redux/userSlice.tsx
  src/styles/firstUser.css
  src/styles/user.css
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
  vite.config.ts
Labels: ⭐ Feature

#62 api 수정에 따른 테스트 루트 변경
  src/test/MentoTest.tsx
Labels: 🐛 BugFix

#63 ✅test: add functionality to share incorrect answer notes
  src/test/ChatRoom.tsx
  src/test/ChatRoomDetail.tsx
  src/test/ChatTest.tsx
  src/test/MentoDetail.tsx
Labels: ✅ Test

#64 Feature/feedback page
  .env.example
  src/pages/Feedback.tsx
  src/styles/feedback.css
Labels: ⭐ Feature, 🎨 Html & Css

#65 [FEAT] 멘토 카드 클릭 시 정보 보내기 + 오답 노트 저장
  src/pages/Feedback.tsx
Labels: 🐛 BugFix, ⭐ Feature
